/ (repo root)
  README.md
  next.config.mjs
  package.json
  tsconfig.json
  public/
    favicon.ico
    og.png
    logos/brand1.svg
    logos/brand2.svg
    logos/brand3.svg
    logos/brand4.svg
  app/
    layout.tsx
    page.mdx
    contact/page.mdx
    about/page.mdx
    work/page.mdx
    work/case-study-aurora.mdx
    work/case-study-ridge.mdx
    services/page.mdx
    services/paid-social.mdx
    services/performance-creative.mdx
    services/strategy.mdx
    blog/page.mdx
    blog/paid-social-audit-checklist.mdx
    blog/landing-page-cro-quickwins.mdx
    privacy/page.mdx
    terms/page.mdx
  components/
    Hero.tsx
    LogoRow.tsx
    StatBar.tsx
    ServiceCard.tsx
    Testimonial.tsx
    CTASection.tsx
    Pricing.tsx
    Newsletter.tsx
  theme.config.tsx
  app/_meta.json
  app/work/_meta.json
  app/services/_meta.json
  app/blog/_meta.json
